name: Ejecutar main.py

on:
  push:
    branches:
      - main

jobs:
  ejecutar_main_py:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ejecutar MAIN.py
        run: |
          cd ReadmeGenerator
          pip install -r requirements.txt
          python main.py
          cd ..
